//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suconbu.Sumacon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("960, 540")]
        public global::System.Drawing.Size MainSize {
            get {
                return ((global::System.Drawing.Size)(this["MainSize"]));
            }
            set {
                this["MainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\screencapture")]
        public string CaptureSaveDirectoryPath {
            get {
                return ((string)(this["CaptureSaveDirectoryPath"]));
            }
            set {
                this["CaptureSaveDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{device-model}_{date}_{time}_{no}.png")]
        public string CaptureFileNamePattern {
            get {
                return ((string)(this["CaptureFileNamePattern"]));
            }
            set {
                this["CaptureFileNamePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaptureContinuousEnabled {
            get {
                return ((bool)(this["CaptureContinuousEnabled"]));
            }
            set {
                this["CaptureContinuousEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CaptureIntervalSeconds {
            get {
                return ((int)(this["CaptureIntervalSeconds"]));
            }
            set {
                this["CaptureIntervalSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CaptureCount {
            get {
                return ((int)(this["CaptureCount"]));
            }
            set {
                this["CaptureCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaptureSkipDuplicateEnabled {
            get {
                return ((bool)(this["CaptureSkipDuplicateEnabled"]));
            }
            set {
                this["CaptureSkipDuplicateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\screenrecord")]
        public string RecordSaveDirectoryPath {
            get {
                return ((string)(this["RecordSaveDirectoryPath"]));
            }
            set {
                this["RecordSaveDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{device-model}_{date}_{time}_{width}x{height}_{duration}_{no}.mp4")]
        public string RecordFileNamePattern {
            get {
                return ((string)(this["RecordFileNamePattern"]));
            }
            set {
                this["RecordFileNamePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1/1")]
        public string RecordViewSize {
            get {
                return ((string)(this["RecordViewSize"]));
            }
            set {
                this["RecordViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string RecordQuality {
            get {
                return ((string)(this["RecordQuality"]));
            }
            set {
                this["RecordQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecordTimestampEnabled {
            get {
                return ((bool)(this["RecordTimestampEnabled"]));
            }
            set {
                this["RecordTimestampEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int RecordLimitTime {
            get {
                return ((int)(this["RecordLimitTime"]));
            }
            set {
                this["RecordLimitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaptureCountEnabled {
            get {
                return ((bool)(this["CaptureCountEnabled"]));
            }
            set {
                this["CaptureCountEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public int CaptureSplitterDistance {
            get {
                return ((int)(this["CaptureSplitterDistance"]));
            }
            set {
                this["CaptureSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int RecordSplitterDistance {
            get {
                return ((int)(this["RecordSplitterDistance"]));
            }
            set {
                this["RecordSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int RecordLimitTimeMax {
            get {
                return ((int)(this["RecordLimitTimeMax"]));
            }
            set {
                this["RecordLimitTimeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/sdcard")]
        public string DeviceTemporaryDirectoryPath {
            get {
                return ((string)(this["DeviceTemporaryDirectoryPath"]));
            }
            set {
                this["DeviceTemporaryDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogFilterPriorityF {
            get {
                return ((bool)(this["LogFilterPriorityF"]));
            }
            set {
                this["LogFilterPriorityF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogFilterPriorityE {
            get {
                return ((bool)(this["LogFilterPriorityE"]));
            }
            set {
                this["LogFilterPriorityE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogFilterPriorityW {
            get {
                return ((bool)(this["LogFilterPriorityW"]));
            }
            set {
                this["LogFilterPriorityW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogFilterPriorityI {
            get {
                return ((bool)(this["LogFilterPriorityI"]));
            }
            set {
                this["LogFilterPriorityI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogFilterPriorityD {
            get {
                return ((bool)(this["LogFilterPriorityD"]));
            }
            set {
                this["LogFilterPriorityD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogFilterPriorityV {
            get {
                return ((bool)(this["LogFilterPriorityV"]));
            }
            set {
                this["LogFilterPriorityV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ControlBeep {
            get {
                return ((bool)(this["ControlBeep"]));
            }
            set {
                this["ControlBeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::Suconbu.Mobile.TouchProtocolType DeviceManagerTouchProtocolType {
            get {
                return ((global::Suconbu.Mobile.TouchProtocolType)(this["DeviceManagerTouchProtocolType"]));
            }
            set {
                this["DeviceManagerTouchProtocolType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainMaximized {
            get {
                return ((bool)(this["MainMaximized"]));
            }
            set {
                this["MainMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int RecordPullDelayMillisecondsAtManualStop {
            get {
                return ((int)(this["RecordPullDelayMillisecondsAtManualStop"]));
            }
            set {
                this["RecordPullDelayMillisecondsAtManualStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScriptText {
            get {
                return ((string)(this["ScriptText"]));
            }
            set {
                this["ScriptText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ScriptStepIntervalMilliseconds {
            get {
                return ((int)(this["ScriptStepIntervalMilliseconds"]));
            }
            set {
                this["ScriptStepIntervalMilliseconds"] = value;
            }
        }
    }
}
